- name: Get composer installer
  shell: "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\""

- name: Run Install script
  shell: "php composer-setup.php"

- name: Make composer.phar runnable from anywhere by adding to PATHed location as 'composer'
  shell: "mv composer.phar /usr/local/bin/composer"

- name: Add composer's bin dir to system-wide $PATH (for drush)
  copy:
    dest: /etc/profile.d/custom-path.sh
    content: 'PATH=$PATH:/home/vagrant/.composer/vendor/bin'

- name: Add simplesaml with composer
  shell: "composer require simplesamlphp/simplesamlphp"