- name: Get composer installer
  shell: "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\""

- name: Run Install script
  shell: "php composer-setup.php"

- name: Make composer.phar runnable from anywhere by adding to PATHed location as 'composer'
  shell: "mv composer.phar /usr/local/bin/composer"

- name: Add composer package path
  shell: "export PATH=\"$HOME/.composer/vendor/bin:$PATH\""